version: '3'
services:
  nginx:
    build: nginx
    container_name: daas_nginx
    volumes:
      - "../app:/var/www/html:rw"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - backend
    #command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php
      - database

  php:
    build: php
    container_name: daas_php
    restart: always
    networks:
      - backend
    volumes:
      - "../app:/var/www/html:rw"

  node:
    build: node
    container_name: daas_node
    restart: always
    networks:
      - backend
    volumes:
      - "../app:/var/www/html:rw"

  database:
    image: mariadb
    container_name: daas_db
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=daas_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3306:3306"

networks:
  backend:
    driver: bridge
